hof/ci: add retry to formatter image dep fetching to reduce failed builds from external issues

diff --git a/formatters/tools/black/Dockerfile.debian b/formatters/tools/black/Dockerfile.debian
--- a/formatters/tools/black/Dockerfile.debian
+++ b/formatters/tools/black/Dockerfile.debian
@@ -19,10 +19,11 @@ RUN apt-get update -y \
 
 WORKDIR /app
 
-# install deps
+# install deps, with retry
 COPY Pipfile Pipfile.lock /app/
-RUN pip install --upgrade pip pipenv \
-	&& pipenv install --deploy --system \
+RUN cmd="pipenv install --deploy --system"; \
+	pip install --upgrade pip pipenv \
+	&& for i in $(seq 1 5); do $cmd && s=0 && break || s=$? && sleep 1; done; (exit $s) \
 	&& pip uninstall -y pipenv
 
 # our server code
diff --git a/formatters/tools/csharpier/Dockerfile.debian b/formatters/tools/csharpier/Dockerfile.debian
--- a/formatters/tools/csharpier/Dockerfile.debian
+++ b/formatters/tools/csharpier/Dockerfile.debian
@@ -13,8 +13,9 @@ RUN cat /tmp/rid
 # Copy everything
 COPY . ./
 
-# Restore as distinct layers
-RUN dotnet restore -r $(cat /tmp/rid)
+# Restore as distinct layer, with retry
+RUN cmd="dotnet restore -r $(cat /tmp/rid)"; \
+	for i in $(seq 1 5); do $cmd && s=0 && break || s=$? && sleep 1; done; (exit $s)
 
 # Build and publish a release
 RUN dotnet publish -c Release -o out -r $RID $(cat /tmp/rid) --self-contained false --no-restore
